### ISSUE TITLE
Audio Only

### ISSUE THREAD

**Issue by MG577** [Satsuoni/widevine-l3-guesser#11]
On prime video I am getting keys that only works with audios .. for video it shows KID not found on the stream error while trying to decrypt ..

Any Solution here ??

**Comment by TiRajo** [comment]
Is prime shows three keys or only 2? Check the video with mp4info what is the exact kid and compare with key results

**Comment by MG577** [comment]
@TiRajo I am getting 3 keys there
and checked the video KID using mp4info .. its not on the gusser result

**Comment by TiRajo** [comment]
ok then your using other mpd file other then streaming one ! download correct one

**Comment by MG577** [comment]
@TiRajo how to get correct mpd ?? and how to download using mpd file

this mpd from network tab wont work with youtube-dl/yt-dlp
https://s3-bom-ww.cf.dash.row.aiv-cdn.net/dm/2$FL2DDicrbJ_rTpsHrV5hhDJzSqk~/5158/2bd2/4691/4384-be11-1a0406cf53af/e64078d9-7799-4b39-a4f3-456bf880c6ee_corrected.mpd?amznDtid=AOAGZA014O5RE&encoding=segmentBase


and actually i am not using any mpd for download ... just searched video on ntwrk tab and got direct download link like this

https://s3-bom-ww.cf.dash.row.aiv-cdn.net/dm/2$FL2DDicrbJ_rTpsHrV5hhDJzSqk~/5158/2bd2/4691/4384-be11-1a0406cf53af/e64078d9-7799-4b39-a4f3-456bf880c6ee_video_1.mp4?amznDtid=AOAGZA014O5RE

**Comment by TiRajo** [comment]
mpd and video has same kid only 

mpd file 
<ContentProtection cenc:default_KID="270C1441-45BC-45AE-848B-6CD9C8EA3881" schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc"/>

mp4 file(mp4info result)
[schi] size=8+32
      [tenc] size=12+20
        default_isProtected = 1
        default_Per_Sample_IV_Size = 8
        default_KID = [**27 0c 14 41 45 bc 45 ae 84 8b 6c d9 c8 ea 38 81**]
    Bytes: 00000000000000010000000000000000000000000000000001e000c800480000004800000000000000010a41564320436f64696e670000000000000000000000000000000000000000000018ffff0000003361766343014d4016ffe1001b674d4016e4303c37f2e02d4040405000003e90000bb808f162d9a001000568e978fc800000001462747274000062bd00046a80000186a00000005073696e660000000c66726d6161766331000000147363686d0000000063656e630001000000000028736368690000002074656e630000000000000108270c144145bc45ae848b6cd9c8ea3881

**Comment by TiRajo** [comment]
> this mpd from network tab wont work with youtube-dl/yt-dlp

use **--allow-unplayable-formats**  to dl the drm files

**Comment by MG577** [comment]
> 
> use **--allow-unplayable-formats** to dl the drm files

bro yeah I use like this, still not working

yt-dlp -F --allow-unplayable-formats "mpd"


> 
> so guesser must have this kid !

this is my KID bro from the video ... and its not there

 default_isProtected = 1
    default_Per_Sample_IV_Size = 8
    default_KID = **[e5 91 a7 03 13 3c 48 9d 85 cd d2 3e f2 fa bd c4]**

**Comment by TiRajo** [comment]
yes guesser will take only playing mpd,kid and results. your doing file which is not in mpd. share the mediainfo of yours file(e5 91 a7 03 13 3c 48 9d 85 cd d2 3e f2 fa bd c4).

**Comment by MG577** [comment]
@TiRajo 

I am getting this error even using **--allow-unplayable-formats**

[generic] e64078d9-7799-4b39-a4f3-456bf880c6ee_corrected: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] e64078d9-7799-4b39-a4f3-456bf880c6ee_corrected: Downloading webpage
[generic] e64078d9-7799-4b39-a4f3-456bf880c6ee_corrected: Extracting information
ERROR: An extractor error has occurred. (caused by KeyError('sourceURL')); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output

**Comment by TiRajo** [comment]
> @TiRajo
> 
> I am getting this error even using **--allow-unplayable-formats**
> 
> [generic] e64078d9-7799-4b39-a4f3-456bf880c6ee_corrected: Requesting header
> WARNING: [generic] Falling back on generic information extractor.
> [generic] e64078d9-7799-4b39-a4f3-456bf880c6ee_corrected: Downloading webpage
> [generic] e64078d9-7799-4b39-a4f3-456bf880c6ee_corrected: Extracting information
> ERROR: An extractor error has occurred. (caused by KeyError('sourceURL')); please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see https://github.com/yt-dlp/yt-dlp on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output

this is due to segments , ?amznDtid=AOAGZA014O5RE**&encoding=segmentBase** add bolded one in url

**Comment by MG577** [comment]
this one bro

Video
ID                          : 1
Format                      : AVC
Format/Info                 : Advanced Video Codec
Format profile              : Main@L2.2
Format settings             : CABAC / 4 Ref Frames
Format settings, CABAC      : Yes
Format settings, Reference  : 4 frames
Codec ID                    : encv / avc1
Codec ID/Info               : Advanced Video Coding
Duration                    : 1 h 20 min
Bit rate mode               : Constant
Bit rate                    : 373 kb/s
Nominal bit rate            : 450 kb/s
Maximum bit rate            : 1 115 kb/s
Width                       : 480 pixels
Height                      : 200 pixels
Display aspect ratio        : 2.40:1
Frame rate mode             : Constant
Frame rate                  : 23.976 (24000/1001) FPS
Color space                 : YUV
Chroma subsampling          : 4:2:0
Bit depth                   : 8 bits
Scan type                   : Progressive
Bits/(Pixel*Frame)          : 0.162
Stream size                 : 216 MiB (99%)
Encryption                  : Encrypted
Color range                 : Limited
Color primaries             : BT.709
Transfer characteristics    : BT.709
Matrix coefficients         : BT.709
Codec configuration box     : avcC

**Comment by TiRajo** [comment]
bolded one differs with your files with same url you shared

ID                          : 1
Format                      : AVC
Format/Info                 : Advanced Video Codec
Format profile              : Main@L2.2
Format settings             : **CABAC / 5 Ref Frames**
Format settings, CABAC      : Yes
Format settings, Reference  : **5 frames**
Codec ID                    : encv / avc1
Codec ID/Info               : Advanced Video Coding
Duration                    : 1 h 20 min
Bit rate                    : 90.9 kb/s
Maximum bit rate            : 289 kb/s
Width                       : 480 pixels
Height                      : 200 pixels
Display aspect ratio        : 2.40:1
Frame rate mode             : Constant
Frame rate                  : 23.976 (24000/1001) FPS
Color space                 : YUV
Chroma subsampling          : 4:2:0
Bit depth                   : 8 bits
Scan type                   : Progressive
Bits/(Pixel*Frame)          : 0.039
Stream size                 : 52.6 MiB (95%)
Encryption                  : Encrypted
Color range                 : Limited
Color primaries             : BT.709
Transfer characteristics    : BT.709
Matrix coefficients         : BT.709
Codec configuration box     : avcC

**Comment by MG577** [comment]
> 
> this is due to segments , ?amznDtid=AOAGZA014O5RE **&encoding=segmentBase** add bolded one in url

thanks alot bro its working now :) showing results

**Comment by TiRajo** [comment]
> > this is due to segments , ?amznDtid=AOAGZA014O5RE **&encoding=segmentBase** add bolded one in url
> 
> thanks alot bro its working now :) showing results

is your using ffmpeg to dl the files?

**Comment by MG577** [comment]
> 
> is your using ffmpeg to dl the files?

u mean direct links (amzn) ?? I use IDM for that lol 

and for MPD, I use YT-DLP bro .. sometimes Youtube-DL

**Comment by TiRajo** [comment]
ok! try mpd via files with decrypt keys it will work sure

**Comment by MG577** [comment]
> bolded one differs with your files with same url you shared

U r right bro .. also on mpd it has lower bilrate

Bit rate : 373 kb/s
Nominal bit rate : 450 kb/s
Maximum bit rate : 1 115 kb/s

vs

Bit rate : 90.9 kb/s
Maximum bit rate : 289 kb/s


while resolution is same

**Comment by MG577** [comment]
> ok! try mpd via files with decrypt keys it will work sure

thanks alot bro for ur help ... I will check today :)

**Comment by 09kkthxbb** [comment]
I use m3u8-dl cli to grab encrypted .mpd files. But all videos always end up in x264 format with encoding settings according to medianfo

How to I download ones that uses h.264 as well?

**Comment by MG577** [comment]
@09kkthxbb yt-dlp should work with ur site 

by the way which site ur trying to dnld ?
