### ISSUE TITLE
Wakanim.tv

### ISSUE THREAD

**Issue by Hilldoc** [Satsuoni/widevine-l3-guesser#12]
Hello. For wakanim.tv it working? If not, possible something to do?

**Comment by HackerBoy0412** [comment]
Is working

**Comment by Hilldoc** [comment]
Screen, please, because, my chrome it's don't looking key\kid wakanim.tv's anime...

**Comment by Hilldoc** [comment]
@Satsuoni can you help?

**Comment by N3ars** [comment]
yes its working 
![hBGab6hDQa](https://user-images.githubusercontent.com/41067116/128608491-5fc7b886-2bad-45ba-b735-a8e6034f73c1.png)

**Comment by Hilldoc** [comment]
> 
> 
> yes its working
> ![hBGab6hDQa](https://user-images.githubusercontent.com/41067116/128608491-5fc7b886-2bad-45ba-b735-a8e6034f73c1.png)

Ru-segment it's working too?

**Comment by Hilldoc** [comment]
![1](https://user-images.githubusercontent.com/88579687/128609390-a7d81974-4c15-417c-a3ea-dad9532e3ba1.jpg)
![2](https://user-images.githubusercontent.com/88579687/128609393-59a4a9cc-aae8-49f8-9455-e8b6871266dc.jpg)

**Comment by Hilldoc** [comment]
@N3ars may be you have special script for working wakanim?

**Comment by Hilldoc** [comment]
@N3ars may be we use another script, or another browser, chrome alternative?

**Comment by N3ars** [comment]
> Eng/Ru-segment decryptor don't looking...
> May be need more special scripts?

I'm using Opera and no i don't use any specific tools, but you can try get the key locally with this tool if its doesn't work (didnt try it). https://github.com/T3rry7f/NoDRM
Normally its the same service providing the key they re using, so no reason to not work with the other language of the site.

![otKq](https://user-images.githubusercontent.com/41067116/128613657-35a67b48-52fd-4c84-af0e-e333547f82e6.png)

The key is working as shown in this screenshot

**Comment by Hilldoc** [comment]
> > Eng/Ru-segment decryptor don't looking...
> > May be need more special scripts?
> 
> I'm using Opera and no i don't use any specific tools, but you can try get the key locally with this tool if its doesn't work (didnt try it). https://github.com/T3rry7f/NoDRM
> Normally its the same service providing the key they re using, so no reason to not work with the other language of the site.
> 
> ![otKq](https://user-images.githubusercontent.com/41067116/128613657-35a67b48-52fd-4c84-af0e-e333547f82e6.png)
> 
> The key is working as shown in this screenshot
> Good luck!

How it NotDRM use/install? I don't know...

**Comment by N3ars** [comment]
I tried the script but it seems to have few problems that i didn't solve, the keys that gives me aren't the correct one, maybe because its not corresponding or needed authorization for the license something like that

**Comment by Hilldoc** [comment]
> 
> 
> I tried the script but it seems to have few problems that i didn't solve, the keys that gives me aren't the correct one, maybe because its not corresponding or needed authorization for the license something like that

I wish ask, maybe you have any specific version your Opera, or Windows? And, what version widevine-l3-decrtyptor you using?

**Comment by N3ars** [comment]
I was on VM Windows 19043.1151 21H1 Opera 78.
https://github.com/nilaoda/widevine-l3-guesser this plugin

**Comment by Hilldoc** [comment]
![1](https://user-images.githubusercontent.com/88579687/128631233-556ac4d0-3ea2-48c2-8e4a-bd7ba41a196d.jpg)
> I was on VM Windows 19043.1151 21H1 Opera 78.
> https://github.com/nilaoda/widevine-l3-guesser this plugin

On screen another version, modified, without call concole browser, but for me all not working only on wakanim...

**Comment by N3ars** [comment]
> On your screen another version, modified, without call concole browser, but for me all not working only on wakanim...

It's exactly the same version it's just the dark theme from https://github.com/CoronaBringer/widevine-l3-guesser

**Comment by Hilldoc** [comment]
I can't understand, why not working decryptor only on wakanim... VPN not help too... unpossible, what only in Russia don't work.

**Comment by N3ars** [comment]
I don't know why isnt working for you ... 
I used a vpn to go to wakanim ru just in case and it seems to work perfectly too.
Maybe you have addon who causes conflict? I dont know...
![p11OzsD](https://user-images.githubusercontent.com/41067116/128633966-da10b9d4-945a-4309-961b-6fb9fe633793.png)

**Comment by N3ars** [comment]
Btw we shouldnt continue discuss here i know wakanim and how they work i dont want to take any risk.

**Comment by Hilldoc** [comment]
Ok. Thanks, what help.

**Comment by Hilldoc** [comment]
Let's delete all message, if you afraid risk.

**Comment by N3ars** [comment]
Yes if you want to contact me on telegram : @Liza_559
