### ISSUE TITLE
popup alert

### ISSUE THREAD

**Issue by amitalokbera** [Satsuoni/widevine-l3-guesser#13]
is there any way to add an alert function to the extension?
so if a key is found it should display the data in popup alert on the browser

Thank You

**Comment by Essam3152** [comment]
You could use this branch with Chrome,

https://github.com/nilaoda/widevine-l3-guesser/tree/modified

**Comment by amitalokbera** [comment]
please dont use this

> You could use this branch with Chrome.
> 
> https://codeload.github.com/nilaoda/widevine-l3-guesser/zip/refs/heads/modified
> 
> https://github.com/nilaoda/widevine-l3-guesser/tree/modified

NOTE - DONT USE THIS FORK, IT HAVE VIRUS

**Comment by Essam3152** [comment]
@amitalokbera Which virus? Could you explain more please?

https://www.virustotal.com/gui/file/9cbffe806c26bdb57392cd474cf1f559c44837e2663f98390aa757ef03995b39/detection

**Comment by amitalokbera** [comment]
then why does that fork library size is 200mb whereas the original one is only 11mb

**Comment by Essam3152** [comment]
@amitalokbera This PR will help you to modify the extension for getting the popup alert.

https://github.com/Satsuoni/widevine-l3-guesser/pull/3/commits/56ad38500d23210ae51fc577b3852824b1dda095

**Comment by RoyRiv3r** [comment]
No it doesn't or it's just a false flag ...

**Comment by Satsuoni** [comment]
Just replace console.log with alert? Or use one of the forks that use alerts, prompts, etc? Or read [Issue #1](https://github.com/Satsuoni/widevine-l3-guesser/issues/1) for my stance on various matters?
