### ISSUE TITLE
Would someone kindly to get the keys for win32?

### ISSUE THREAD

**Issue by gflogix** [Satsuoni/widevine-l3-guesser#14]
Under the win32 platform, the following information is displayed: "Can't verify license request signature; either the platform is wrong or the key has changed!"
Would someone kindly to get the keys for win32?

 @Satsuoni @knobse

**Comment by MG577** [comment]
Yeah @Satsuoni we need one for 32bit too .. please bro

**Comment by zackmark29** [comment]
Don't expect any update from the Author.

_"I will probably cease updating repo soon after Readme is finished, so for people that want it modified: please fork or copy it and modify as you see fit. Attribution is appreciated, though ;)"_

The end._

**Comment by RoyRiv3r** [comment]
Who still uses win32 in the current year? 
i thought win32 was over and only devs & company still use it for compatibility problem

**Comment by Satsuoni** [comment]
> Don't expect any update from the Author.
> 
> _"I will probably cease updating repo soon after Readme is finished, so for people that want it modified: please fork or copy it and modify as you see fit. Attribution is appreciated, though ;)"_
> 
> The end._

Indeed. Also read #5 I don't feel like spending another ~1.5 months on key extraction, and I did describe procedure in... reasonable(?)... detail. It is easy enough to do, just time-consuming.

**Comment by knobse** [comment]
@gflogix if you can send me the 32bit dll i can put the public key here but someone will probably still need to go after the private exponent & other stuff to make this extension work.
