### ISSUE TITLE
Donation?

### ISSUE THREAD

**Issue by gt02x** [Satsuoni/widevine-l3-guesser#15]
Hi, Satsuoni, I have sent an email for donation. Can you reply it please?

**Comment by Satsuoni** [comment]
I got one (guess first one fell into spam). FWIW, #1 has my Bitcoin address :) In the beginning somewhere. Thank you for your consideration. I really don't feel worthy though XD

**Comment by EnthusiastAnon** [comment]
> 
> 
> I really don't feel worthy though XD

You should. 
You gave as a way to beat this malignant tumor, easily! 
You gave us a way to collect, store and share content with others that one day might not be available.
And that's priceless, my friend.

**Comment by gt02x** [comment]
> I got one (guess first one fell into spam). FWIW, #1 has my Bitcoin address :) In the beginning somewhere. Thank you for your consideration. I really don't feel worthy though XD

No, Your job is well done. I just donated $500 to 1N12PaTwaULMLJjmQdggerBYRzcJ6kQCx3 . Please check email also. Thanks.

**Comment by Satsuoni** [comment]
Thank you (and other donators) very　much :) 

> You should.
> You gave as a way to beat this malignant tumor, easily!
> You gave us a way to collect, store and share content with others that one day might not be available.
> And that's priceless, my friend.

For the moment.  That said, I claim this repo as a parody/educational material, since I personally don't use it to download anything, and just get a good chuckle when I see keys in the console <_< So its primary goal is amusement/personal satisfaction. How *you* use it is up to you ◔_◔

**Comment by EnthusiastAnon** [comment]
> For the moment. 

Oh, there'll be another moment, or another hero like you. Until they patch this up, you'll be rested and you'll want another go at their new protection :D

> and just get a good chuckle when I see keys in the console 

I get a nice dose of dopamine :D

> How _you_ use it is up to you ◔_◔

Yes, and that's also one more argument for its greatness!
