### ISSUE TITLE
Update key for decrypt HDR videos on NF

### ISSUE THREAD

**Issue by georgysaumen** [Satsuoni/widevine-l3-guesser#19]
Hello, @Satsuoni 

I have use your key extension to get key decrypt but I think your extension cannot get key for HDR picture format! I have download 1 video of VN country and they support HDR but when I decrypt and use the key that extension give I see that all the key I have cannot decrypt for HDR, after decryt and I use MediaInfo to check I see that HDR line is disappear so I think the key that I use to decrypt is not use for decrypt HDR videos! Can you find ways to get key decrypt for HDR ?

Example of HDR videos link (this video is in Vietnamese so you need to fake IP to VN to see that):  https://www.netflix.com/watch/81405167

This is the encrypted HDR video I have download on the link above:   https://drive.google.com/file/d/1zMVVAaAsckDM9UeFt8xC0Fvy-zaXCSVa/view?usp=sharing

![image](https://user-images.githubusercontent.com/86090065/130344277-8f5aef33-23d8-4a25-820e-e7735652d21e.png)

(Here is the example of the video I have type link above after download and not decrypt)

Thanks!

**Comment by mzikagate** [comment]
i think  its hard to get hdr keys from chrome

**Comment by georgysaumen** [comment]
> i think its hard to get hdr keys from chrome

Sad for saying that! 😔 Hope @Satsuoni can update this!

**Comment by gt02x** [comment]
You can't. Widevine L3 which is a software backed DRM can only support resolutions below 720p. All upper resolutions should be required and protected with Widevine L1 which is hardware backed. This is Google's recommendation and most providers with valuable content comply.
