### ISSUE TITLE
Does it support decrypting tencent drm video? like ‘全职法师第五季超前点播’

### ISSUE THREAD

**Issue by YFTX2015** [Satsuoni/widevine-l3-guesser#20]

**Comment by ortegabae** [comment]
@YFTX2015  to be able to download on that site use this tool https://github.com/jaysonlong/webvideo-downloader
I hope this helps

**Comment by YFTX2015** [comment]
I just used that tool, and it could only download these videos, but could not play them, especially ep7 to ep12.

**Comment by Satsuoni** [comment]
Does not seem to be related.
