### ISSUE TITLE
Not a valid origin for the client: https://<company>.udemy.com

### ISSUE THREAD

**Issue by hoangphuc2019** [Satsuoni/widevine-l3-guesser#21]
I got the error message in `console` tab in Developer mode.
`details: "Not a valid origin for the client: https://<company>.udemy.com has not been registered for client ID 700206021005-as1xxxxxxxx70msgjhma1krf3k9q.apps.googleusercontent.com. Please go to https://console.developers.google.com/ and register this origin for your project's client ID."`

**Comment by Satsuoni** [comment]
I don't know? It does not seem to be related to extension.
