### ISSUE TITLE
Looking For A Developer

### ISSUE THREAD

**Issue by coin4sports** [Satsuoni/widevine-l3-guesser#22]
See below messages

**Comment by Satsuoni** [comment]
I am not currently interested in long-term job, but if it is just a tool or two... maybe? Depends on what you mean by "tools". Could you elaborate?

**Comment by coin4sports** [comment]
See below messages

**Comment by Satsuoni** [comment]
Sorry for asking, but isn't most of what you described, if not all, done by ffmpeg? It can download, decrypt, mux, and I think create HLS stream as well... Pretty sure it can be adapted to the purpose? I might be wrong, I guess. (also, my email is around my profile somewhere)

**Comment by EnthusiastAnon** [comment]
@Satsuoni no, your e-mail is not around your profile somewhere. I can't be that of a Github noob to not see it.

**Comment by coin4sports** [comment]
See below messages

**Comment by Satsuoni** [comment]
Hmm, I know ffmpeg can download mpd files, so urllib should be unnecessary, but it seems that decryption_key in ffmpeg is not compatible with cenc, etc, so, that would not work... If it were up to me, I would have either slapped together a shell file in Linux (using temporary file) or mashed together sources of mp4decrypt and ffmpeg, though that would have taken a while. Hmm, not sure I want to bother with setup though, see: lazy. 

@EnthusiastAnon : Unlike you people, I am kind of a n00b when it comes to github, so I am not sure where people keep finding my email to write to me directly, but they manage. Maybe there is direct message function? Dunno *shrug*

**Comment by EnthusiastAnon** [comment]
@Satsuoni They are probably getting it from somewhere else.
I spent 30 minutes on googling Satsuoni and couldn't find an e-mail unfortunately.
Would really like to know what am I missing :D

**Comment by Essam23** [comment]
@EnthusiastAnon See here.

https://www.nymeria.io/blog/how-to-manually-find-email-addresses-for-github-users

https://github.com/Satsuoni/widevine-l3-guesser/commit/5cbf7693b6909a6e4badc1921af5fbe1e5ef0b95.patch

**Comment by EnthusiastAnon** [comment]
@Essam3152 marvelous. Thank you. Now I forgot what I wanted to write to him >_>

**Comment by Satsuoni** [comment]
Right, my git settings. I thought they used my articles. Ah well.

**Comment by alienmaster9** [comment]
@coin4sports  if you are looking for live stream restream i got plenty of tools @alienmaster9 telegram find it

**Comment by Satsuoni** [comment]
Please refer to my email, etc...
