### ISSUE TITLE
fix elge

### ISSUE THREAD

**Issue by momoko2806** [Satsuoni/widevine-l3-guesser#7]
Please fix for microsoft elge

**Comment by TiRajo** [comment]
it works well with edge. trun off the PlayReady drm so that  will get key shown

**Comment by momoko2806** [comment]
How to turn off playready??

**Comment by momoko2806** [comment]
I turn off this but netflix show 720p...

**Comment by TiRajo** [comment]
yep edge use playready for higher bitrate ! even chrome can bring higher bitrate than edge in widevine

**Comment by momoko2806** [comment]
I use chrome but netflix show 720 is highest

**Comment by TiRajo** [comment]
> I use chrome but netflix show 720 is highest

use https://github.com/truedread/netflix-1080p/releases/tag/v1.21 to push 1080p netflix

**Comment by momoko2806** [comment]
I have been fixed thanks
