### ISSUE TITLE
Background Branch Error (Noisy debug)

### ISSUE THREAD

**Issue by TiRajo** [Satsuoni/widevine-l3-guesser#9]
Hello the new update(Noisy debug) works good on 1st load but on refreshing or changing the site, movie gives wrong keys wanted exit the browser and open again it works perfect.

Edit:

https://user-images.githubusercontent.com/88180312/128055353-dcaa0cf0-e667-498c-894a-041181200ed7.PNG : **correct keys log**

https://user-images.githubusercontent.com/88180312/128055471-9d1348a5-e996-407f-9f3f-9742cdece7fd.PNG : **Wrong keys log**

**Comment by Satsuoni** [comment]
Since the update was mostly about adding debug logging, I am not sure what may have caused that...

**Comment by TiRajo** [comment]
only in Background branch has this issues ! not every time on rare case it happens on dual key sites.

**Comment by Satsuoni** [comment]
Hmm. Maybe background messaging is wrong, then. I can tweak a bit, but no guarantees, as usual.
